41x41:
  begin: "B"
  end : "E"
  passage: " "
  wall: "+"
61x31:
  begin: "B"
  end : "E"
  passage: "*"
  wall: "o"
81x81:
  begin: "B"
  end : "E"
  passage: "x"
  wall: "."
plus_maze:
  begin: "B"
  end:   "E"
  wall:  "+"
  passage: " "

